### ISSUE TITLE
Do CI on Windows with Appveyor

### ISSUE THREAD

**Issue by jvdb** [parsingdata/metal#137]

**Comment by jvdb** [comment]
http://www.yegor256.com/2015/01/10/windows-appveyor-maven.html

**Comment by jvdb** [comment]
Thanks! That will make this a whole lot easier :-) And maybe I can even do without the caching (but hey if it works...)

**Comment by DavyLandman** [comment]
no problem.

The caching can be turned off, biggest impact would be that the build log gets a bit noisy, as there are many lines of maven redownloading the dependencies.

Now the cache is cleared after the pom.xml is changed, and in the other cases, the .m2 directory is restored from the previous run.
