### ISSUE TITLE
Remove parse()-method that does not have the scope argument

### ISSUE THREAD

**Issue by jvdb** [parsingdata/metal#15]
It's somehow tempting for anonymous Token-implementations to use the wrong parse()-invocation. We can simply resolve this by removing it.

**Comment by jvdb** [comment]
However, this means that every invocation either needs to provide an explicit `scope` argument or we need some other mechanism to make it easy to run a `parse()`.

**Comment by rdvdijk** [comment]
Solved by implementing #11.
