### ISSUE TITLE
Failure expected at compile time when seq token contains less then 2 tokens

### ISSUE THREAD

**Issue by mvanaken** [parsingdata/metal#167]
The shorthand of `seq` expects a vararg of Tokens, while it is mandatory to have at least two tokens. If this condition is not met, this will throw an `IllegalArgumentException`. I would have expected that the shorthand would fail at compile time instead of run time.

I would propose to adapt the shorthand to have two mandatory tokens and that the third is a vararg.

**Comment by jvdb** [comment]
Excellent point and idea. I think maybe both the `Shorthand` _and_ the actual constructors need this.

**Comment by mvanaken** [comment]
Well, I thought changing the constructors has a bigger impact, since e.g. Christophe has reimplemenations for them. To allow backwards compatibility, that would require multiple constructors, but that would break the ArgumentsTests, which check if the Token classes all have 1 constructor.

Anyhoe, I have created a pull request (my first on github ever!) as a start, but I could extend it. We can talk about it when you are back in town. ;)

**Comment by ccreeten** [comment]
Nice improvement! As far as I can tell, it should not break the reimplementations, only code which explicitely passed an array of tokens (which I used in some thesis peeling, so that will be broken :cry:)? Better yet, with 6.0, the reimplementations have a high chance of becoming useless due to the trampoline improvements.

**Comment by jvdb** [comment]
In principle, someone's reimplementations should never be a reason to either do or not do something. Apart from that, this milestone will likely obsolete those reimplementations so it doesn't matter anyway.
