### ISSUE TITLE
Improve ParseValue toString()

### ISSUE THREAD

**Issue by rdvdijk** [parsingdata/metal#18]
[Currently](https://github.com/parsingdata/metal/blob/7de6188bfd316c08dad33bfca6ed0fd46580a9b2/src/main/java/io/parsingdata/metal/data/ParseValue.java#L71), the implementation is as follows:

```java
@Override
public String toString() {
    return "ParseValue(" + getName() + ":" + super.toString() + ")";
}
```

And the [current](https://github.com/parsingdata/metal/blob/7de6188bfd316c08dad33bfca6ed0fd46580a9b2/src/main/java/io/parsingdata/metal/expression/value/Value.java#L66) superclass `Value` `toString()` method is:

```java
@Override
public String toString() {
    return getClass().getSimpleName() + "(" + DatatypeConverter.printHexBinary(_data) + ")";
}
```

Resulting in duplicate classnames like `ParseValue(value:ParseValue(01))`, where it would be more logical to just have `ParseValue(value:01)"`.

**Comment by jvdb** [comment]
Agree it looks weird now, but maybe an even shorter one than you suggest can help make toString() dumps more readable during debugging. Maybe omit the "value:" as well.

**Comment by rdvdijk** [comment]
In this case `value` was the name of the `ParseValue`, so let's not omit that one :smile:

**Comment by jvdb** [comment]
Or value(01)...

**Comment by jvdb** [comment]
Or even just 01 or in that case 0x01.

ParseValue is the *only* way to store a value in the ParaeGraph, so naming it explicitly seems unnecessary.

**Comment by rdvdijk** [comment]
Let's not forget to remove that `_branched` boolean.
