### ISSUE TITLE
Let ValueExpression.eval() return a collection of Values instead of a single Value

### ISSUE THREAD

**Issue by jvdb** [parsingdata/metal#20]
This will make it easier to generalize complex operations and predicates. An example is a Zip operation that operates on two collections.

Furthermore it will make the combinators more modular -- instead of having separate First, Last, etc. implementations, Ref can simply return all instances which can then be modified by generic First, Last, etc. modifiers.

**Comment by jvdb** [comment]
What is the shape of the returned collection? It would make sense to use `ParseValueList` for this purpose since that's very close to what we need. However, it stores `ParseValue` objects, not `OptionalValue` objects (which is what `ValueExpression.eval()` returns now).

We can either change `ParseValueList` to store `OptionalValue` objects, but then we'll have to consider what this means for the current user of `ParseValueList` (`ParseGraph.getAll()`). In that situation it doesn't make sense to have `OptionalValue` objects because it only returns meaningful (i.e., non-empty) objects. So we're then essentially weakening the interface but requiring users to check each object.

Another option is to clone `ParseValueList` to `OptionalValueList`, but that seems a bit dodgy too. We could use generics to prevent code clones, but I'm not sure it's worth the cognitive overhead of having complicated and several very similar objects types around.

This then brings us to the point of whether we really need `OptionalValue` objects in the returned collection from `ValueExpression.eval()`. If we say no, then this means that empty objects will be omitted. This can be problematic if you want to do a Zip operation and one of the result drops out. If we don't have optionals, this will misalign the results and mess things up.

An example: Zip with divide on [2, 4, 6] and [2, 0, 3]. Result would be [1, NaN, 2] with optionals, or [1, 2] without. In the second case, which one is missing?

**Comment by jvdb** [comment]
What should the semantics be for `ComparisonExpression` implementations? Some ideas:

1. Only accept lists of length 1, implement current behaviour.
2. Compare the lists in some way. For example compare left[0] to right[0], left[1] to right[1], etc. But there may be additional approaches that make sense, such as compare all values in left to all values in right?

It's tempting to just go for 1, but maybe we're losing some interesting potential uses? @rdvdijk?

**Comment by jvdb** [comment]
Another thing to consider: `Con` constructors that accept multiple values and return a list containing them.

**Comment by jvdb** [comment]
I've made some decisions in current implementations:

1. `Offset` returns the offset of all ParseValues in case of a list.
2. `Elvis` determines a result to be good if the list contains *any* non-empty value.
3. `RepN` and `Nod` throw an exception if more than one value is provided.

**Comment by rdvdijk** [comment]
Shall I comment on the commits? Or maybe create a pull request and gather the comments there?

**Comment by rdvdijk** [comment]
> What should the semantics be for ComparisonExpression implementations? Some ideas:
> 
> 1. Only accept lists of length 1, implement current behaviour.
> 2. Compare the lists in some way. For example compare left[0] to right[0], left[1] to right[1], etc. But there may be additional approaches that make sense, such as compare all values in left to all values in right? How is the final result determined, with an and operator?
> It's tempting to just go for 1, but maybe we're losing some interesting potential uses? @rdvdijk?

Let's "entertain" a few examples:

1. Let's say we want to `eq` a list with another list. I think it would make sense that **all** the bytes should be equal.
2. Let's say we want to `gtNum` a list with another list. My intuition: **all** values should be larger than the other list.

I have a hard time coming up with an actual use case, though.

Doiing "1" would be trivial using the `first` operator.

**Comment by jvdb** [comment]
> If we choose for "2", doing "1" would be trivial using the first operator.

Agreed. So that's quite a strong argument for doing a linear comparison (0->0, 1->1, etc.), since it's still easy to fall back to original behaviour if desired.

> Also: what to do with lists of unequal size? That should probably result in false, or even throw an Exception.

Not sure. My intuition would say that it would result in a `false`, since there will be a comparison involving `empty` which yields false. Exception would probaby create a lot of weird errors on non-standard or corrupt files. But then again, maybe an exception is easier to debug than a weird parse error?

**Comment by jvdb** [comment]
`FoldLeft` and 'FoldRight` need to be looked at specifically, since there are many opportunities for implementation choices that lead to subtle changes in semantics.

**Comment by rdvdijk** [comment]
> How is the final result determined, with an and operator?

The final result would just be a collection of booleans. Or does that go too far?

**Comment by jvdb** [comment]
> > How is the final result determined, with an and operator?

> The final result would just be a collection of booleans. Or does that go too far?

What we're changing now is that `ValueExpression.eval(...)` returns a list instead of a value. `ComparisonExpression` is derived from `Expression`, which has a different `eval(...)` that returns a boolean.

At the same time, I think it's a very cool idea -- that `Expression` also returns a list (of booleans in this case). But that actually doesn't change the question of when a predicate is considered to be `true`? When all values are `true` (and)? When at least one is `true` (or)? Or something else?

We could make that configurable of course, with something like `all(predicate)` or `one(predicate` or something like that. But then we probably still want a default. Unless we want to force everyone to specify this specifically for *every* predicate.

**Comment by jvdb** [comment]
The only part not converted at this point is `Sub`. What should happen when you provide a list to `Sub`? It's easy to require a single value, but I think it might be useful to handle them all. For example, a table with addresses to a collection of data structures can then be dereferenced and parsed together. But the question then is: if one fails, or if the list contains an `empty` value, should the entire thing roll back? Probably :)

**Comment by jvdb** [comment]
All tests succeed again! Now to add a bunch of tests to exercise some of the extended behaviour.

**Comment by jvdb** [comment]
Stuff to add tests for:

*List processing by `ValueExpressions`:*

1. `ComparisonExpressions` now compare all values when lists are provided.
2. `Elvis` operator now checks whether the left expression returns at least one non-empty value.
3. Perhaps some alternative list expressions as addition to the `Ref()` ones for `Fold(*)`.
4. `Not`, `Offset` and `Ref` process and/or return lists.

*Token processing:*

5. `Nod` and `RepN` do not accept multiple values.
6. `Sub` processes an entire list.

Additionally:

7. Check whether JPEG, PNG and ZIP can be described more elegantly with improved and expanded functionality.

**Comment by jvdb** [comment]
This adds some tests for A1 and B1 (`Nod`).

**Comment by jvdb** [comment]
Tests completed: A1, all B and C (C is moved to a separate issue for the 4.0.0 release, #54).

**Comment by rdvdijk** [comment]
About A2: I think the Elvis operator should apply to each pair of values in the lists and return a new list of values. That way, the "normal" behavior `elvis(a, b)` would become `first(elvis(list-with-a, list-with-b))`.

If `ω` is an 'empty' value:

```
[ 1 ] elvis [ 2 ] => [ 1 ]
[ ω ] elvis [ 2 ] => [ 2 ]
[ ω ] elvis [ ω ] => [ ω ]

[ 1, 2 ] elvis [ 3 ,4 ] => [ 1, 2 ]
[ ω, 2 ] elvis [ 3 ,4 ] => [ 3, 2 ]
[ 1, ω ] elvis [ 3 ,4 ] => [ 1, 4 ]
[ ω, ω ] elvis [ ω ,4 ] => [ ω, 4 ]
```

What happens to lists that do not have equal length?

**Comment by jvdb** [comment]
@rdvdijk Great idea. In general I think it's better to have `Elvis` produce some kind of list result that handles the inputs as pairs instead of some difficult to trace compound operations.

> What happens to lists that do not have equal length?

This however is a problem. Maybe it's cleanest if we treat it as a regular `BinaryValueExpression`? Then we get cartesian product, which works fine with different length lists. Plus the semantics of `first(elvis(list-with-a, list-with-b))` is still the same as before.

**Comment by jvdb** [comment]
We can't use `BinaryValueExpression` for `Elvis` because it handles evaluation of the operands (which the implementation of `Elvis` needs to do itself to determine the return value).

**Comment by jvdb** [comment]
@rdvdijk: Implemented your proposal. With regard to lists of unequal length:

```
[ 1, 2, 3 ] elvis [ 4 ,5 ] => [ 1, 2, 3 ]
[ 1, 2 ] elvis [ 3 ,4, 5 ] => [ 1, 2, 5 ]
[ 1, ω, 3 ] elvis [ 4, 5, ω, 7 ] => [ 1, 5, 3, 7 ]
[ ω ] elvis [ ω, 3, ω ] => [ ω, 3, ω ]
```

**Comment by jvdb** [comment]
Based on experience with `elvis`, changed `BinaryValueExpression` behaviour to linear. Result now has length of longest input list, padded with `ω`. Some examples with the `+` operator (`add`):

```
[ 1, 2 ] + [ 3, 4 ] => [ 4, 6 ]
[ 1, 2, 3 ] + [ 4 ,5 ]       => [ 5, 7, ω ]
[ 1, 2 ] + [ 3 ,4, 5 ]    => [ 4, 6, ω ]
[ 1, ω, 3 ] + [ 4, 5, ω, 7 ] => [ 5, ω, ω, ω ]
[ ω ] + [ ω, 3, ω ]    => [ ω, ω, ω ]
```

**Comment by jvdb** [comment]
This completes tests for A3, A4 and A5.
