### ISSUE TITLE
Create ByToken#getAll(Token definition)

### ISSUE THREAD

**Issue by rdvdijk** [parsingdata/metal#22]
[ByToken](https://github.com/parsingdata/metal/blob/9a7668ea07ea035f888999486a3779f842951784/src/main/java/io/parsingdata/metal/data/selection/ByToken.java) does not have a `getAll` similar to `ByName#getAll`.

**Comment by jvdb** [comment]
Do we need it specifically for something now, or just as general utility?

Not that I think it's a bad idea, in fact, if we manage to implement #20, we will need it for the inevitable Ref(Token) implementation. However, this does suggest that we should probably remove ParseValueList altogether... But this then brings up the point of semantics for other ValueExpressions.

Simply put: what does Add() mean on a ParseGraph and a ParseRef?
