### ISSUE TITLE
Include verification in ParameterizedParse tests if stream is fully parsed.

### ISSUE THREAD

**Issue by mvanaken** [parsingdata/metal#243]
The ParameterizedParse tests test if we are able (or not able) to parse a given token on a given stream. However, this test does not verify if we have also parsed the whole stream, in case it succeeds. We should include this check in the test. This makes it much easier to verify parsing results for new features.

**Comment by jvdb** [comment]
Oh this is a really good idea! I hope it doesn't interfere with any existing tests though (but then we should probably just fix them).
