### ISSUE TITLE
Add a "locally scoped" ref to avoid unpredictable references in recursive Token definitions

### ISSUE THREAD

**Issue by DavyLandman** [parsingdata/metal#250]
Given the following pseudo-java code which has a recursive Token `A`:

```java
final Token A = seq("A",
    def("b", con(1)), 
    token("AorB"), 
    def("c", con(1), ge(last(ref("A.b")))
);
final Token B = seq("B", def("a", con(1)));
final Token AorB = cho("AorB", A, B);
```

It seems impossible to calculate how far back in the `ref("A.b")` stream we have to look to get the `b` field that was parsed at the same level of recursion (or is nesting the better term)?

I would like to propose an alternative to `ref` which is a ref that only searches the local stack and higher, not in the children.

(problem discovered together with @pinoval )

**Comment by DavyLandman** [comment]
After some more discussion and considering cases with @pinoval, it might be that we need a kind of stackfull reference. So that we can also pass along a value expression to a function, that keeps on referring to this stack, even though it's used at a deeper level

**Comment by jvdb** [comment]
Sounds interesting!

I think my initial approach will be to solve the case as described at the top. I have some fairly simple ideas, but I'm not sure if they will work. It is quite possible that if those solutions solve this case that they are not adequate for what you are doing -- but that would be the time to come up with a new sample case :)

The most basic approach will be to implement a `ValueExpression` that refers to a value's current _scope_ with regard to referencing other values. So basically this would allow you to create scopes on the fly based on where you are. I will create a branch for the working test case and possible solutions.

**Comment by DavyLandman** [comment]
I've tried to create a horrible example:

```java
    final Token A = seq("A", def("b", con(1)), ABC, d(last(ref("A.b"))));
    final Token B = seq("B", def("b", con(1)), d(last(ref("B.b"))));
    final Token C = seq("C", def("b", con(1)));
    final Token ABC = cho("ABC", A, B, C);

    final Token d(ValueExpression x) {
        return seq("D_dynamic", ABC, def("c", con(1), eq(x)));
    }
```

The `d` function is a way to reduce duplication, we've seen this pattern before in other metal examples, and its quite a useful one. But with the recursive/nested structures, it's impossible to pass it the right ValueExpression that points to the correct field at the correct nesting level.

> The most basic approach will be to implement a ValueExpression that refers to a value's current scope with regard to referencing other values. So basically this would allow you to create scopes on the fly based on where you are. I will create a branch for the working test case and possible solutions.

This sounds like it might be good enough, even for the above example.

**Comment by DavyLandman** [comment]
For completeness sake, I wanted to add another example that @pinoval and I worked on:

```java
    private static final Token Lower200 = def("lowValue", con(1), ltEqNum(con(200)));

    private static final Token CheckedREP = seq("CheckedREP",
        def("magic", con(2), eq(con(42,42))),
        rep("items", Lower200), 
        def("countCheck", con(4), eqNum(len(ref("CheckedREP.items"))))
    );

    private static final Token RepTwice = seq("Container",
        CheckedREP,
        CheckedREP // now for this one, how will `countCheck` be scoped to only get the items inside this CheckedREP, and not the previous one as well?
    );
```

**Comment by jvdb** [comment]
Thanks for more examples, I will turn them all into actual test cases!

**Comment by DavyLandman** [comment]
There are more complex examples to think of, when you start making a recursive data structure, but I'll leave those to your appetite.
