### ISSUE TITLE
Add a fully dynamic token, more powerfull than tie 

### ISSUE THREAD

**Issue by DavyLandman** [parsingdata/metal#251]
We encountered this problem while working with IP and TCP streams. Before you can assemble a full TCP packet, you might have to wait for all the IP messages to be parsed, so that you can reassemble the fragment IP in such a way that it can be parsed as TCP messages.

I think that for this case, and maybe others, we need plain old imperative  code that mangles with the order of the fragments and calls the token parser on correct subslices of the bytes.

Example with pseudo-java:

```java
final Token Stream = seq("Stream"
    rep("packets", IP),
    calculate("messages", assembleAndParse(ref("Stream.packets")
));

final token IP= seq("IP", 
    def("len", con(1)), 
    def("fragmentId", con(1)), 
    def("fragmentOffset", con(1)), 
    def("data", last(ref(“IP.len”)))
);

final token TCP = seq("TCP", ....);

ParseGraph assembleAndParse(ParseGraph[] packets) {
    return reassemble(packets)
       .map( (ByteSlice packet) -> TCP.parse(packet))
       .collect(MetalCollectors.rep(TCP));
}
```

I'm leaving out the details of the `reassamble` method, but in essence it will take the `IP.fragementId` and the `IP.fragmentOffset` and the order they appear in the stream and figure out how it should be assembled (the way it's assembled differs per OS and can be used to hide stuff from firewalls and packet inspection software).

So, the interface of the `calculate` is not that clear yet. But the point is that the `let` hack with the `tie` is not sufficient, as we have to keep the shape of the data, and especially with a `rep` their is no guarantee it will be maintained after unparse & parse.

(discovered together with @pinoval)

**Comment by jvdb** [comment]
I've encountered similar issues, but I'm closing this issue now because it's almost 5 years old 😅
