### ISSUE TITLE
Exception when def size is greater than Integer.MAX_VALUE

### ISSUE THREAD

**Issue by ccreeten** [parsingdata/metal#310]
When a `def` has a size larger than that of a max integer, an exception is thrown during parsing of the data. An example test which triggers this can be found [here](https://github.com/ccreeten/metal/commit/d582f9e9d18ce92c83bf305c85e9166eb2befaba).

It was a bit unexpected, with the knowledge that Metal is lazy, and the fact that we never read the resulting data but only use the slice offset and length. The reason is that the ByteStreamSource implementation always converts the BigInteger length to an int using `intValueExact`. It is of course related with the fact that the reading part of the Source API returns a byte array (as do parts within Metal, all the way back to Value).

**Comment by jvdb** [comment]
It looks like the actual `BigInteger` conversion can be pushed further down so that it's more lazy and a scenario such as this can be made to work.
