### ISSUE TITLE
Document all public items

### ISSUE THREAD

**Issue by jvdb** [parsingdata/metal#9]
- [x] document `Token`s
- [ ] document `Shorthand`s
- [x] document `ComparisonExpression`s
- [x] document `LogicalExpression`s
- [x] document `ValueExpression`s
...

**Comment by rdvdijk** [comment]
@jvdb I've ported my previously written `Token` documentation to the `document-public-items` branch. This documentation needs to be reviewed (it's was written over a year ago), and the new `TokenRef` still needs documentation.

This is all far from complete, but it's a start.

**Comment by rdvdijk** [comment]
(@gertjanal Here you go, it's a start :wink:)

**Comment by jvdb** [comment]
In PR #134, all but the `Shorthand` Javadoc is present. Pending possible changes to the `Shorthand` (such as removing it and moving all the methods to their respective classes and factory methods) I suggest we keep it like this for now.

**Comment by DavyLandman** [comment]
I for one was missing the javadocs on the shorthand method. Especially as a new user, that is the place you start (since the example formats use it).

**Comment by jvdb** [comment]
@DavyLandman Good point... We're also contemplating generating `Shorthand` entirely... It's essentially a fixed transformation based on the constructors/Javadoc present in all `Token` and `ValueExpression` subclasses :) But I'll try to add something like what you suggest to the upcoming 6.0 release.
